#!/bin/bash

TOKEN = $INPUT_TOKEN
REPO = $INPUT_REPO
REF = $INPUT_REF
PROJECT_PATH = $INPUT_PATH
GITLAB_HOST = $INPUT_GITLAB_HOST
GITLAB_USER = $INPUT_USER

git clone --origin $REF https://$GITLAB_USER:$TOKEN@$GITLAB_HOST/$REPO.git $PROJECT_PATH